### ISSUE TITLE
Second level bullet indenting

### ISSUE THREAD

**Issue by Zachu** [nmartin84/admonition-panels#8]
Hi! And thanks for the cool plugin!

Is this by-design, a bug, or perhaps a mismatch with some of my plugins? My second level bullets are indented weirdly:
![image](https://user-images.githubusercontent.com/1262488/213194585-50c08e3c-9b8c-4801-9ee7-29ead0f56961.png)

I would expect the second level to be similarly indented than the further ones. Taking away the admon tag it looks like this:
![image](https://user-images.githubusercontent.com/1262488/213194781-de0f9072-8c18-4b28-80eb-3b51d1c3c561.png)

And block content is this
```md
- Test admon  
	- First level  
		- Second level  
			- Third level  
				- Fourth level  
					- Fifth level  
```

I haven't yet tried disabling every single of my plugins but I did try to disable the few ones I thought might have any affect here.

I'm running on the latest marketplace version of this module and Logseq `0.8.16` on Linux machine.

**Comment by Zachu** [comment]
I did manage to fix it with following `custom.css` entry:
```css
/* Fix admon-panel second-level indentation */
div[data-refs-self*="admon-"] > .block-children-container > .block-children > .ls-block > .block-children-container > .block-children {
  margin-left: 20px;
}
```

Not sure if there's a better way to target that one or if the 20px even is like correct amount of margin but it works for me =)
